# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-tn-jetson-bsp"
BBFILE_PATTERN_meta-tn-jetson-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-tn-jetson-bsp = "60"

LAYERDEPENDS_meta-tn-jetson-bsp = "core"
LAYERSERIES_COMPAT_meta-tn-jetson-bsp = "wrynose"
